---CRIAR BANCO DE DADOS

CREATE DATABASE HealthClinic

--- CRIAR TABELAS

CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(40)NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	Nome VARCHAR(30)NOT NULL,
	Email VARCHAR(20)NOT NULL UNIQUE,
	Senha VARCHAR(20)NOT NULL
)

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL,
	Nome VARCHAR(20)NOT NULL,
	DataNascimento DATE NOT NULL,
	Telefone VARCHAR(20)NOT NULL UNIQUE,
	CPF VARCHAR(11)NOT NULL UNIQUE
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(30)NOT NULL,
	NomeFantasia VARCHAR(20)NOT NULL,
	RazaoSocial VARCHAR(20)NOT NULL UNIQUE
)

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20)NOT NULL
)

CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(200)NOT NULL
)

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)NOT NULL,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade)NOT NULL,
	CRM VARCHAR(20)NOT NULL UNIQUE
)

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico)NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente)NOT NULL,
	IdComentario INT FOREIGN KEY REFERENCES Comentario(IdComentario)NOT NULL,
	[Data] DATE NOT NULL,
	Horario TIME NOT NULL,
	Prontuario VARCHAR(200)NOT NULL
)